version: '3.8'

services:
  potential-nav:
    image: potential-nav:0.0
    container_name: potential-nav
    network_mode: host
    restart: always
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - FASTDDS_BUILTIN_TRANSPORTS=UDPv4
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/root/ros_ws/src/potential-nav
    stdin_open: true
    command: bash -c "chmod +x /root/ros_ws/src/potential-nav/start_nav.sh && /root/ros_ws/src/potential-nav/start_nav.sh"